### PR TITLE
Tanks spawn at bases

### PR DESCRIPTION
**Pull request by bhatnathan**
Now the tank spawns at their respective bases instead of in the middle of the map.
Tanks only spawn once gameworld and harvester (in that order) have been scanned (you can still debug with the computer with 'Q' but the computer's tank won't spawn at the base then).

### CODE REVIEW

**Comment by bhatnathan** [comment]
This pull request fixes issue #64

**Comment by bhatnathan** [comment]
Noticed a bug, DON'T MERGE, fixing now

**Comment by bhatnathan** [comment]
Tanks now spawn at their bases correctly (yes, even if they are the computer)

**Review by schnigle — APPROVED** [review]
Works.

**Pull request merged**
