### PR TITLE
Animated Tracks

### PR DESCRIPTION
**Pull request by agylling**
… it moves sort of all the time and both tracks at the same time, gonna adjust it later with individual track 3d models.

It's animated by offseting the Texture of the tracks renderer. 
I'm aware that it sometimes moves when the tank stands still. Will fix after hello world.

### CODE REVIEW

**Comment by agylling** [comment]
I don't know if the script will catch the tracks of the tank when they spawn in real time rather when loading the scene.

**Comment by schnigle** [comment]
Start is called when the object is created, so that should not be a problem. There are however problems when using multiple tanks or renaming the tanks, so I recommend exposing an inspector reference instead. The reference will then be kept within the local hierarchy for different prefab instances, so we don't run into issues when using multiple tanks.

There is also a new merge conflict on tankMovement.cs since we merged the other changes before merging this one. Be aware that we have changed the location of tankMovement.cs.

**Comment by agylling** [comment]
I think I've understood the problem with inspector reference you were talking about. I have merged with the other script so that is resolved as well. However I do get a "bug" now that the tracks animate very slowly forward when going forward with the tracks, but properly when going backwards. I can't seem to find the answer to that :/

**Review by schnigle — APPROVED** [review]
It's not exactly the solution I had in mind, but it seems to work well now with multiple tanks, parenting and renaming, so I guess it should be good enough.

**Pull request merged**
